### ISSUE TITLE
Label for internal changes which nonetheless merit a release

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/interesting-category-action#3]
There are a fair number of cases like https://github.com/jenkinsci/support-core-plugin/pull/360 where a PR is not terribly interesting from a user perspective—some dependency bumps, POM wrangling—yet we need a release anyway, in order to feed into `jenkinsci/bom` or other dependencies or tooling. There should be a label (and I guess RD category) for this purpose, which should be displayed in an unexciting section of release notes yet still be considered interesting by this action.

Workarounds:
* use `bug` or `enhancement` and risk confusing end users
* merge, wait for trunk CI to be green (which could take up to an hour), then manually trigger the CD action

**Comment by jetersen** [comment]
We could use developer?
https://github.com/jenkinsci/.github/blob/ddd4660711fd559b0fc4696747b81546297485c2/.github/release-drafter.yml#L38-L40

**Comment by jetersen** [comment]
It is already setup to work with developer: 👷 
https://github.com/jenkins-infra/interesting-category-action/blob/1a2c10ae989cba9b76a95e0f0364aaf4f9642218/action.yaml#L13

**Comment by jglick** [comment]
Probably close enough, yes.

**Comment by jetersen** [comment]
Created the label in `jenkinsci/bom` feel free to change the color: 
![image](https://user-images.githubusercontent.com/1661688/164026535-1fca4756-21b9-49bc-b840-70b9096bff4d.png)

**Comment by jetersen** [comment]
FYI @basil @timja related to `jenkinsci/bom` release

Of course could be relevant for others when we go around bumping BOM and POM to suggest that they use the label `developer` when using CD and release drafter.
